version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: flask_postgres_db
    restart: always
    environment:
      POSTGRES_DB: counters_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-app:
    build:
      context: .   
      dockerfile: Dockerfile  
    container_name: flask_counter_app
    restart: always
    ports:
      - "8000:5000"  
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/counters_db
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY}  
    env_file:
      - .env  

volumes:
  pgdata:
